// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_clouds[] =
"<?xml version=\"1.0\"?>"
"<!-- clouds.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.clouds</name>"
"        <implementation>csClouds</implementation>"
"        <description>Dynamic cloud simulation and rendering system</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>";
  #ifndef csClouds_FACTORY_REGISTER_DEFINED 
  #define csClouds_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csClouds) 
  #endif

class clouds
{
SCF_REGISTER_STATIC_LIBRARY(clouds,metainfo_clouds)
  #ifndef csClouds_FACTORY_REGISTERED 
  #define csClouds_FACTORY_REGISTERED 
    csClouds_StaticInit csClouds_static_init__; 
  #endif
public:
 clouds();
};
clouds::clouds() {}

}
