// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_makehuman[] =
"<?xml version=\"1.0\"?>"
"<!-- makehuman.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.animesh.makehuman</name>"
"        <implementation>MakehumanManager</implementation>"
"        <description>Makehuman generation of animated meshes</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef MakehumanManager_FACTORY_REGISTER_DEFINED 
  #define MakehumanManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(MakehumanManager) 
  #endif

class makehuman
{
SCF_REGISTER_STATIC_LIBRARY(makehuman,metainfo_makehuman)
  #ifndef MakehumanManager_FACTORY_REGISTERED 
  #define MakehumanManager_FACTORY_REGISTERED 
    MakehumanManager_StaticInit MakehumanManager_static_init__; 
  #endif
public:
 makehuman();
};
makehuman::makehuman() {}

}
