// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_cseditorspaces[] =
"<?xml version=\"1.0\"?>"
"<!-- cseditorspaces.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.editor.plugin.core.cs3dspace</name>"
"        <implementation>CS3DSpace</implementation>"
"        <description>3D View</description>"
"        <allowMultiple>false</allowMultiple>"
"      </class>"
"      <class>"
"        <name>crystalspace.editor.plugin.core.propertiesspace</name>"
"        <implementation>PropertiesSpace</implementation>"
"        <description>Properties</description>"
"        <allowMultiple>true</allowMultiple>"
"      </class>"
"      <!--"
"      <class>"
"        <name>crystalspace.editor.plugin.core.scenebrowserpanel</name>"
"        <implementation>SceneBrowserPanel</implementation>"
"        <description>CSEditor Scene Browser Panel</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.editor.plugin.core.assetbrowserpanel</name>"
"        <implementation>AssetBrowserPanel</implementation>"
"        <description>CSEditor Asset Browser Panel</description>"
"      </class>"
"      -->"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef CS3DSpace_FACTORY_REGISTER_DEFINED 
  #define CS3DSpace_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(CS3DSpace) 
  #endif
  #ifndef PropertiesSpace_FACTORY_REGISTER_DEFINED 
  #define PropertiesSpace_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(PropertiesSpace) 
  #endif
  #ifndef SceneBrowserPanel_FACTORY_REGISTER_DEFINED 
  #define SceneBrowserPanel_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(SceneBrowserPanel) 
  #endif
  #ifndef AssetBrowserPanel_FACTORY_REGISTER_DEFINED 
  #define AssetBrowserPanel_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(AssetBrowserPanel) 
  #endif

class cseditorspaces
{
SCF_REGISTER_STATIC_LIBRARY(cseditorspaces,metainfo_cseditorspaces)
  #ifndef CS3DSpace_FACTORY_REGISTERED 
  #define CS3DSpace_FACTORY_REGISTERED 
    CS3DSpace_StaticInit CS3DSpace_static_init__; 
  #endif
  #ifndef PropertiesSpace_FACTORY_REGISTERED 
  #define PropertiesSpace_FACTORY_REGISTERED 
    PropertiesSpace_StaticInit PropertiesSpace_static_init__; 
  #endif
  #ifndef SceneBrowserPanel_FACTORY_REGISTERED 
  #define SceneBrowserPanel_FACTORY_REGISTERED 
    SceneBrowserPanel_StaticInit SceneBrowserPanel_static_init__; 
  #endif
  #ifndef AssetBrowserPanel_FACTORY_REGISTERED 
  #define AssetBrowserPanel_FACTORY_REGISTERED 
    AssetBrowserPanel_StaticInit AssetBrowserPanel_static_init__; 
  #endif
public:
 cseditorspaces();
};
cseditorspaces::cseditorspaces() {}

}
