// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_enginepersist[] =
"<?xml version=\"1.0\"?>"
"<!-- persist.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.engine.persist</name>"
"        <implementation>Persist</implementation>"
"        <description>Crystal Space Engine Core Resource Loader/Saver</description>"
"        <requires>"
"          <class>crystalspace.engine.3d</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef Persist_FACTORY_REGISTER_DEFINED 
  #define Persist_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(Persist) 
  #endif

class enginepersist
{
SCF_REGISTER_STATIC_LIBRARY(enginepersist,metainfo_enginepersist)
  #ifndef Persist_FACTORY_REGISTERED 
  #define Persist_FACTORY_REGISTERED 
    Persist_StaticInit Persist_static_init__; 
  #endif
public:
 enginepersist();
};
enginepersist::enginepersist() {}

}
