// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_fileloader[] =
"<?xml version=\"1.0\"?>"
"<!-- fileloader.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.loader.file</name>"
"        <implementation>FileLoader</implementation>"
"        <description>Crystal Space file resource loader</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef FileLoader_FACTORY_REGISTER_DEFINED 
  #define FileLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(FileLoader) 
  #endif

class fileloader
{
SCF_REGISTER_STATIC_LIBRARY(fileloader,metainfo_fileloader)
  #ifndef FileLoader_FACTORY_REGISTERED 
  #define FileLoader_FACTORY_REGISTERED 
    FileLoader_StaticInit FileLoader_static_init__; 
  #endif
public:
 fileloader();
};
fileloader::fileloader() {}

}
