// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_occluvis[] =
"<?xml version=\"1.0\"?>"
"<!-- occluvis.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.culling.occluvis</name>"
"        <implementation>csOccluVis</implementation>"
"        <description>Occlusion Query Visibility System</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csOccluVis_FACTORY_REGISTER_DEFINED 
  #define csOccluVis_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csOccluVis) 
  #endif

class occluvis
{
SCF_REGISTER_STATIC_LIBRARY(occluvis,metainfo_occluvis)
  #ifndef csOccluVis_FACTORY_REGISTERED 
  #define csOccluVis_FACTORY_REGISTERED 
    csOccluVis_StaticInit csOccluVis_static_init__; 
  #endif
public:
 occluvis();
};
occluvis::occluvis() {}

}
