// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_cseditordamn[] =
"<?xml version=\"1.0\"?>"
"<!-- cseditordamn.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.editor.plugin.damn.damnspace</name>"
"        <implementation>DAMNSpace</implementation>"
"        <description>DAMN View</description>"
"        <allowMultiple>true</allowMultiple>"
"      </class>"
"      "
"      <class>"
"        <name>crystalspace.resources.managers.damn</name>"
"        <implementation>DAMNResourceManager</implementation>"
"        <description>DAMN Resource Manager</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef DAMNSpace_FACTORY_REGISTER_DEFINED 
  #define DAMNSpace_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(DAMNSpace) 
  #endif
  #ifndef DAMNResourceManager_FACTORY_REGISTER_DEFINED 
  #define DAMNResourceManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(DAMNResourceManager) 
  #endif

class cseditordamn
{
SCF_REGISTER_STATIC_LIBRARY(cseditordamn,metainfo_cseditordamn)
  #ifndef DAMNSpace_FACTORY_REGISTERED 
  #define DAMNSpace_FACTORY_REGISTERED 
    DAMNSpace_StaticInit DAMNSpace_static_init__; 
  #endif
  #ifndef DAMNResourceManager_FACTORY_REGISTERED 
  #define DAMNResourceManager_FACTORY_REGISTERED 
    DAMNResourceManager_StaticInit DAMNResourceManager_static_init__; 
  #endif
public:
 cseditordamn();
};
cseditordamn::cseditordamn() {}

}
