// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_cseditorpanels[] =
"<?xml version=\"1.0\"?>"
"<!-- cseditorspaces.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.editor.plugin.core.objectpanel</name>"
"        <implementation>ObjectPanel</implementation>"
"        <description>Object Panel</description>"
"        <space>crystalspace.editor.plugin.core.propertiesspace</space>"
"      </class>"
"      "
"      <class>"
"        <name>crystalspace.editor.plugin.core.camerapanel</name>"
"        <implementation>CameraPanel</implementation>"
"        <description>Camera Panel</description>"
"        <space>crystalspace.editor.plugin.core.propertiesspace</space>"
"      </class>"
"      "
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef ObjectPanel_FACTORY_REGISTER_DEFINED 
  #define ObjectPanel_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(ObjectPanel) 
  #endif
  #ifndef CameraPanel_FACTORY_REGISTER_DEFINED 
  #define CameraPanel_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(CameraPanel) 
  #endif

class cseditorpanels
{
SCF_REGISTER_STATIC_LIBRARY(cseditorpanels,metainfo_cseditorpanels)
  #ifndef ObjectPanel_FACTORY_REGISTERED 
  #define ObjectPanel_FACTORY_REGISTERED 
    ObjectPanel_StaticInit ObjectPanel_static_init__; 
  #endif
  #ifndef CameraPanel_FACTORY_REGISTERED 
  #define CameraPanel_FACTORY_REGISTERED 
    CameraPanel_StaticInit CameraPanel_static_init__; 
  #endif
public:
 cseditorpanels();
};
cseditorpanels::cseditorpanels() {}

}
