// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_rm_test1[] =
"<?xml version=\"1.0\"?>"
"<!-- rm_test1.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.rendermanager.test1</name>"
"        <implementation>RMTest1</implementation>"
"        <description>Render manager - test1</description>"
"        <requires>"
"          <class>crystalspace.engine.</class>"
"          <class>crystalspace.graphics3d.</class>         "
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef RMTest1_FACTORY_REGISTER_DEFINED 
  #define RMTest1_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(RMTest1) 
  #endif

class rm_test1
{
SCF_REGISTER_STATIC_LIBRARY(rm_test1,metainfo_rm_test1)
  #ifndef RMTest1_FACTORY_REGISTERED 
  #define RMTest1_FACTORY_REGISTERED 
    RMTest1_StaticInit RMTest1_static_init__; 
  #endif
public:
 rm_test1();
};
rm_test1::rm_test1() {}

}
