// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_opentreeldr[] =
"<?xml version=\"1.0\"?>"
"<!-- opentreeldr.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.loader.factory.opentree</name>"
"        <implementation>csOpenTreeFactoryLoader</implementation>"
"        <description>Crystal Space OpenTree Factory Loader</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.loader.opentree</name>"
"        <implementation>csOpenTreeMeshLoader</implementation>"
"        <description>Crystal Space OpenTree Mesh Loader</description>"
"      </class>"
"      <!--class>"
"        <name>crystalspace.mesh.saver.factory.protomesh</name>"
"        <implementation>csProtoFactorySaver</implementation>"
"        <description>Crystal Space Proto Mesh Factory Saver</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.saver.protomesh</name>"
"        <implementation>csProtoMeshSaver</implementation>"
"        <description>Crystal Space Proto Mesh Mesh Saver</description>"
"      </class-->"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csOpenTreeFactoryLoader_FACTORY_REGISTER_DEFINED 
  #define csOpenTreeFactoryLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csOpenTreeFactoryLoader) 
  #endif
  #ifndef csOpenTreeMeshLoader_FACTORY_REGISTER_DEFINED 
  #define csOpenTreeMeshLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csOpenTreeMeshLoader) 
  #endif
  #ifndef csProtoFactorySaver_FACTORY_REGISTER_DEFINED 
  #define csProtoFactorySaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csProtoFactorySaver) 
  #endif
  #ifndef csProtoMeshSaver_FACTORY_REGISTER_DEFINED 
  #define csProtoMeshSaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csProtoMeshSaver) 
  #endif

class opentreeldr
{
SCF_REGISTER_STATIC_LIBRARY(opentreeldr,metainfo_opentreeldr)
  #ifndef csOpenTreeFactoryLoader_FACTORY_REGISTERED 
  #define csOpenTreeFactoryLoader_FACTORY_REGISTERED 
    csOpenTreeFactoryLoader_StaticInit csOpenTreeFactoryLoader_static_init__; 
  #endif
  #ifndef csOpenTreeMeshLoader_FACTORY_REGISTERED 
  #define csOpenTreeMeshLoader_FACTORY_REGISTERED 
    csOpenTreeMeshLoader_StaticInit csOpenTreeMeshLoader_static_init__; 
  #endif
  #ifndef csProtoFactorySaver_FACTORY_REGISTERED 
  #define csProtoFactorySaver_FACTORY_REGISTERED 
    csProtoFactorySaver_StaticInit csProtoFactorySaver_static_init__; 
  #endif
  #ifndef csProtoMeshSaver_FACTORY_REGISTERED 
  #define csProtoMeshSaver_FACTORY_REGISTERED 
    csProtoMeshSaver_StaticInit csProtoMeshSaver_static_init__; 
  #endif
public:
 opentreeldr();
};
opentreeldr::opentreeldr() {}

}
